[package]
name = "rpztar"
version = "0.1.0"
edition = "2018"

[dependencies]
flate2 = "*"
nix = "*"
tar = "*"

[profile.release]
opt-level = 'z'  # Optimize for size
lto = true
codegen-units = 1
panic = 'abort'
